#!/usr/bin/env bash
# This scripts adds subdomains to my domain provider
# It displays information about my domain

if  [ "$2" ]; then
	ipadd=$(dig +short "$2.$1") 
	record_type=$(dig "$2.$1" | grep -A1 'ANSWER SECTION' | awk 'NR==2' | awk '{print $4}')
	echo "The subdomain $2 is a $record_type record and points to $ipadd"
else
	domain="$1"
	func() {
	local subdomain="$1"
	ipadd=$(dig +short "$subdomain.$domain")

	record_type=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION' | awk 'NR==2' | awk '{print $4}')
	echo "The subdomain $subdomain is a $record_type and points to $ipadd"
	}	

	func "www"
	func "lb-01"
	func "web-01"
	func "web-02"
fi
